image: ubuntu

init:
  - appveyor version
  - sh: echo $APPVEYOR_BUILD_WORKER_IMAGE
  - sh: echo $APPVEYOR_BUILD_WORKER_CLOUD

test_script:
  - cat ~/.config/NuGet/NuGet.Config
  - dotnet tool install -g Cake.Tool

build: off
